export { default as Navbar } from "./Navbar";
export { default as Hero } from "./Hero";
export { default as TrustedBy } from "./TrustedBy";
export { default as Features } from "./Features";
export { default as Stats } from "./Stats";
export { default as Pricing } from "./Pricing";
export { default as CTA } from "./CTA";
export { default as Footer } from "./Footer";
export { default as LanguageSwitcher } from "./LanguageSwitcher";