import { StyleSheet } from 'react-native';

type Colors = {
  bg: string;
  card: string;
  cardSoft: string;
  text: string;
  textMuted: string;
  border: string;
  primary: string;
  nav: string;
};

export function createStyles(colors: Colors) {
  const radius = {
    sm: 10,
    md: 12,
    lg: 14,
    xl: 18,
  };
  const spacing = {
    xs: 6,
    sm: 8,
    md: 10,
    lg: 12,
  };
  const softShadow = {
    shadowColor: '#0F172A',
    shadowOpacity: 0.08,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 6 },
    elevation: 3,
  } as const;

  return StyleSheet.create({
    screen: { flex: 1, backgroundColor: colors.bg },
    centerScreen: { flex: 1, backgroundColor: colors.bg, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 20 },
    authCard: { width: '100%', maxWidth: 420, borderRadius: 18, backgroundColor: colors.card, padding: 18, gap: 10, borderWidth: 1, borderColor: colors.border },
    loginBackdrop: {
      position: 'absolute',
      width: '100%',
      height: '100%',
      overflow: 'hidden',
    },
    loginOrb: {
      position: 'absolute',
      borderRadius: 999,
    },
    loginOrbPrimary: {
      width: 260,
      height: 260,
      top: -80,
      right: -80,
      backgroundColor: `${colors.primary}22`,
    },
    loginOrbSoft: {
      width: 220,
      height: 220,
      bottom: -70,
      left: -70,
      backgroundColor: `${colors.border}88`,
    },
    authCardModern: {
      width: '100%',
      maxWidth: 420,
      borderRadius: 28,
      backgroundColor: colors.card,
      paddingHorizontal: 20,
      paddingTop: 22,
      paddingBottom: 18,
      gap: 12,
      borderWidth: 1,
      borderColor: colors.border,
      shadowColor: '#0F172A',
      shadowOpacity: 0.1,
      shadowRadius: 20,
      shadowOffset: { width: 0, height: 10 },
      elevation: 8,
    },
    loginBrandRow: { flexDirection: 'row', alignItems: 'center', gap: 8 },
    loginBrandIcon: { width: 32, height: 32, borderRadius: 10, alignItems: 'center', justifyContent: 'center' },
    loginHeadline: { color: colors.text, fontSize: 22, fontWeight: '800', letterSpacing: -0.4, marginTop: 2 },
    brandTitle: { fontSize: 24, fontWeight: '800', color: colors.text },
    subtleText: { color: colors.textMuted, fontSize: 13 },
    oauthButton: { borderRadius: 12, paddingVertical: 13, alignItems: 'center', borderWidth: 1 },
    oauthButtonModern: {
      borderRadius: 14,
      paddingVertical: 13,
      alignItems: 'center',
      borderWidth: 1,
      shadowColor: '#111827',
      shadowOpacity: 0.06,
      shadowRadius: 8,
      shadowOffset: { width: 0, height: 4 },
      elevation: 2,
    },
    oauthRow: { flexDirection: 'row', alignItems: 'center', gap: 8 },
    kakaoButton: { backgroundColor: '#FEE500', borderColor: '#E7D13F' },
    googleButton: { backgroundColor: colors.card, borderColor: colors.border },
    kakaoText: { color: '#111111', fontWeight: '700' },
    googleText: { fontWeight: '700' },

    header: {
      paddingHorizontal: 12,
      paddingTop: 8,
      paddingBottom: 10,
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
      backgroundColor: colors.nav,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
    },
    headerHint: { color: colors.textMuted, fontSize: 12, fontWeight: '600' },
    logoArea: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      marginRight: 8,
    },
    logoIcon: {
      width: 30,
      height: 30,
      borderRadius: 8,
      alignItems: 'center',
      justifyContent: 'center',
    },
    logoText: { color: '#fff', fontWeight: '800', fontSize: 16 },
    appTitle: { color: colors.text, fontSize: 18, fontWeight: '800', letterSpacing: -0.4 },
    workspaceSelector: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      paddingHorizontal: 10,
      paddingVertical: 7,
      borderRadius: 10,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.cardSoft,
      marginHorizontal: 8,
    },
    wsTypeDot: { width: 7, height: 7, borderRadius: 4 },
    wsName: { flex: 1, fontSize: 13, fontWeight: '600', color: colors.text },
    modeDropdownButton: {
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: 10,
      paddingHorizontal: 12,
      paddingVertical: 8,
      backgroundColor: colors.cardSoft,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
    },
    modeDropdownText: { fontSize: 12, color: colors.text, fontWeight: '700' },
    modeDropdownChevron: { fontSize: 10, color: colors.textMuted },
    headerActions: { flexDirection: 'row', gap: 8 },
    headerActionButton: {
      width: 36,
      height: 36,
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: 10,
      backgroundColor: colors.card,
      alignItems: 'center',
      justifyContent: 'center',
      position: 'relative',
    },
    headerActionText: { fontSize: 11, color: colors.text, fontWeight: '700' },
    badge: {
      position: 'absolute',
      top: 2,
      right: 2,
      minWidth: 16,
      height: 16,
      borderRadius: 8,
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: 3,
      backgroundColor: '#EF4444',
    },
    badgeText: { color: '#fff', fontSize: 9, fontWeight: '800' },

    modeDropdownMenu: { marginHorizontal: 12, marginTop: 8, borderWidth: 1, borderColor: colors.border, borderRadius: 12, backgroundColor: colors.card, padding: 8, gap: 6 },
    modeMenuItem: { borderRadius: 8, paddingHorizontal: 10, paddingVertical: 9, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.cardSoft },
    modeMenuItemActive: { borderColor: colors.primary, backgroundColor: colors.card },
    modeMenuText: { fontSize: 12, color: colors.textMuted, fontWeight: '600' },
    modeMenuTextActive: { color: colors.text },
    modeMenuCreate: { borderRadius: 8, paddingHorizontal: 10, paddingVertical: 9, borderWidth: 1, borderColor: colors.primary, backgroundColor: colors.card },
    modeMenuCreateText: { color: colors.primary, fontSize: 12, fontWeight: '700' },
    modeMenuLogout: { borderRadius: 8, paddingHorizontal: 10, paddingVertical: 9, borderWidth: 1, borderColor: '#FCA5A5', backgroundColor: colors.card },
    modeMenuLogoutText: { color: '#EF4444', fontSize: 12, fontWeight: '700' },

    workspaceRow: { paddingVertical: 10, paddingHorizontal: 12, borderBottomWidth: 1, borderBottomColor: colors.border, backgroundColor: colors.nav },
    workspacePill: {
      marginRight: 8,
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: 999,
      paddingHorizontal: 13,
      paddingVertical: 8,
      backgroundColor: colors.cardSoft,
      shadowColor: '#0F172A',
      shadowOpacity: 0.05,
      shadowRadius: 6,
      shadowOffset: { width: 0, height: 2 },
      elevation: 1,
    },
    workspacePillActive: { backgroundColor: colors.card, borderColor: colors.primary, shadowOpacity: 0.12, elevation: 3 },
    workspacePillText: { color: colors.textMuted, fontSize: 12, fontWeight: '700' },
    workspacePillTextActive: { color: colors.text },

    teamCreatePanel: { marginHorizontal: 12, marginTop: 8, borderWidth: 1, borderColor: colors.border, borderRadius: 12, backgroundColor: colors.card, padding: 12, gap: 8 },
    planButton: { borderWidth: 1, borderColor: colors.border, borderRadius: 10, paddingHorizontal: 10, paddingVertical: 10, backgroundColor: colors.cardSoft, gap: 2 },
    planTitle: { fontSize: 13, fontWeight: '700', color: colors.text },
    planDesc: { fontSize: 11, color: colors.textMuted },

    content: { flex: 1, backgroundColor: colors.bg },
    contentContainer: { padding: 12, paddingBottom: 24, gap: 10 },
    section: { gap: 10 },
    sectionTitle: { fontSize: 18, fontWeight: '800', color: colors.text },
    panel: { borderWidth: 1, borderColor: colors.border, borderRadius: 14, backgroundColor: colors.card, padding: 12, gap: 8 },
    formTitle: { fontSize: 13, fontWeight: '700', color: colors.text },
    input: { borderWidth: 1, borderColor: colors.border, borderRadius: 10, paddingHorizontal: 10, paddingVertical: 9, backgroundColor: colors.card, color: colors.text },
    memoInput: { borderWidth: 1, borderColor: colors.border, borderRadius: 10, paddingHorizontal: 10, paddingVertical: 10, minHeight: 120, backgroundColor: colors.card, color: colors.text, textAlignVertical: 'top' },

    primaryButton: { backgroundColor: colors.primary, borderRadius: 10, alignItems: 'center', paddingVertical: 11 },
    primaryButtonHalf: { flex: 1, backgroundColor: colors.primary, borderRadius: 10, alignItems: 'center', paddingVertical: 11 },
    primaryButtonText: { color: '#ffffff', fontWeight: '700', fontSize: 13 },
    secondaryButtonHalf: { flex: 1, backgroundColor: colors.cardSoft, borderRadius: 10, alignItems: 'center', paddingVertical: 11, borderWidth: 1, borderColor: colors.border },
    secondaryButtonText: { color: colors.text, fontWeight: '700', fontSize: 13 },

    listRow: { borderWidth: 1, borderColor: colors.border, borderRadius: 12, backgroundColor: colors.card, padding: 11, gap: 5 },
    itemTitle: { color: colors.text, fontWeight: '700', fontSize: 13 },
    itemMeta: { color: colors.textMuted, fontSize: 12 },

    memoTabScroll: { maxHeight: 44 },
    memoTab: { marginRight: 8, borderWidth: 1, borderColor: colors.border, borderRadius: 8, paddingHorizontal: 11, paddingVertical: 8, backgroundColor: colors.card },
    memoTabText: { color: colors.textMuted, fontSize: 12, fontWeight: '600' },

    grid: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
    gridCard: { width: '48%', borderWidth: 1, borderColor: colors.border, borderRadius: 12, backgroundColor: colors.card, padding: 12 },
    gridLabel: { color: colors.textMuted, fontSize: 12 },
    gridValue: { color: colors.text, fontSize: 24, fontWeight: '800', marginTop: 3 },

    notificationBox: { marginHorizontal: 0, marginTop: 0, borderWidth: 1, borderColor: colors.border, borderRadius: 12, backgroundColor: colors.card, padding: 10, gap: 8 },
    notificationRow: { borderWidth: 1, borderColor: colors.border, borderRadius: 10, backgroundColor: colors.cardSoft, padding: 9 },
    queueBanner: {
      marginHorizontal: 0,
      marginTop: 0,
      borderWidth: 1,
      borderColor: colors.primary,
      borderRadius: 12,
      backgroundColor: colors.card,
      paddingHorizontal: 10,
      paddingVertical: 9,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 10,
    },
    queueBannerText: {
      flex: 1,
      color: colors.text,
      fontSize: 12,
      fontWeight: '700',
    },
    queueBannerButton: {
      borderRadius: 8,
      borderWidth: 1,
      borderColor: colors.primary,
      paddingHorizontal: 10,
      paddingVertical: 6,
      backgroundColor: colors.cardSoft,
    },
    queueBannerButtonText: {
      color: colors.primary,
      fontSize: 12,
      fontWeight: '800',
    },

    appBody: {
      flex: 1,
      flexDirection: 'row',
      minHeight: 0,
    },
    leftSidebar: {
      width: 248,
      borderRightWidth: 1,
      borderRightColor: colors.border,
      backgroundColor: colors.nav,
      paddingHorizontal: 10,
      paddingVertical: 12,
      gap: 10,
    },
    leftSidebarCollapsed: {
      width: 76,
    },
    sidebarTopRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      minHeight: 36,
    },
    sidebarTopLabel: {
      color: colors.text,
      fontSize: 14,
      fontWeight: '800',
      letterSpacing: -0.2,
    },
    sidebarToggleButton: {
      width: 30,
      height: 30,
      borderRadius: radius.sm,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.card,
      alignItems: 'center',
      justifyContent: 'center',
    },
    sidebarWorkspaceSwitcher: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: spacing.sm,
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: radius.md,
      backgroundColor: colors.card,
      paddingHorizontal: spacing.md,
      paddingVertical: spacing.sm,
      ...softShadow,
    },
    sidebarWorkspaceSwitcherCollapsed: {
      justifyContent: 'center',
      paddingHorizontal: 0,
    },
    sidebarWorkspaceSwitcherTextWrap: {
      flex: 1,
      minWidth: 0,
    },
    sidebarWorkspaceSwitcherTitle: {
      color: colors.text,
      fontSize: 12,
      fontWeight: '800',
    },
    sidebarWorkspaceSwitcherSub: {
      color: colors.textMuted,
      fontSize: 11,
      fontWeight: '600',
      marginTop: 2,
    },
    sidebarNav: {
      gap: 6,
    },
    sidebarNavButton: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: radius.md,
      backgroundColor: colors.cardSoft,
      paddingHorizontal: 10,
      paddingVertical: 10,
    },
    sidebarNavButtonCollapsed: {
      justifyContent: 'center',
      paddingHorizontal: 0,
    },
    sidebarNavButtonActive: {
      borderColor: colors.primary,
      backgroundColor: colors.card,
      shadowColor: '#0F172A',
      shadowOpacity: 0.12,
      shadowRadius: 8,
      shadowOffset: { width: 0, height: 4 },
      elevation: 4,
    },
    sidebarNavText: {
      color: colors.textMuted,
      fontSize: 13,
      fontWeight: '700',
    },
    sidebarNavTextActive: {
      color: colors.text,
    },
    sidebarDivider: {
      height: 1,
      backgroundColor: colors.border,
      marginVertical: 2,
    },
    sidebarSectionTitle: {
      color: colors.textMuted,
      fontSize: 11,
      fontWeight: '700',
      letterSpacing: 0.5,
      textTransform: 'uppercase',
      paddingHorizontal: 4,
    },
    sidebarWorkspaceScroll: {
      flex: 1,
      minHeight: 0,
    },
    sidebarWorkspaceContainer: {
      gap: 6,
      paddingBottom: 8,
    },
    sidebarWorkspaceItem: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: radius.sm,
      backgroundColor: colors.cardSoft,
      paddingHorizontal: 10,
      paddingVertical: 9,
    },
    sidebarWorkspaceItemCollapsed: {
      justifyContent: 'center',
      paddingHorizontal: 0,
    },
    sidebarWorkspaceItemActive: {
      borderColor: colors.primary,
      backgroundColor: colors.card,
    },
    sidebarWorkspaceText: {
      flex: 1,
      color: colors.textMuted,
      fontSize: 12,
      fontWeight: '700',
    },
    sidebarWorkspaceTextActive: {
      color: colors.text,
    },
    sidebarMainContent: {
      flex: 1,
      minWidth: 0,
      backgroundColor: colors.bg,
      paddingHorizontal: spacing.lg,
      paddingVertical: spacing.lg,
      gap: spacing.md,
    },
    mainTopBar: {
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: radius.xl,
      backgroundColor: colors.card,
      paddingHorizontal: 14,
      paddingVertical: 12,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 10,
      ...softShadow,
    },
    mainTopTitle: {
      color: colors.text,
      fontSize: 18,
      fontWeight: '800',
      letterSpacing: -0.2,
    },
    mainTopSubtitle: {
      color: colors.textMuted,
      fontSize: 12,
      fontWeight: '600',
      marginTop: 2,
    },
    mainTopActions: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: spacing.xs,
    },
    mainTopActionButton: {
      minWidth: 36,
      height: 36,
      borderRadius: radius.sm,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.cardSoft,
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: 8,
      position: 'relative',
    },
    mainTopActionText: {
      color: colors.text,
      fontSize: 11,
      fontWeight: '700',
    },
    mainSlotArea: {
      flex: 1,
      minHeight: 0,
    },

    emptyText: { color: colors.textMuted, fontSize: 12, textAlign: 'center', paddingVertical: 16 },
    errorText: { color: '#EF4444', fontSize: 12 },
    webViewErrorBanner: {
      position: 'absolute',
      left: 10,
      right: 10,
      bottom: 10,
      borderRadius: 10,
      borderWidth: 1,
      borderColor: '#FCA5A5',
      backgroundColor: colors.card,
      paddingHorizontal: 10,
      paddingVertical: 8,
    },
    webViewErrorText: { color: '#EF4444', fontSize: 12, fontWeight: '700' },

    bottomTabs: {
      position: 'absolute',
      left: 0,
      right: 0,
      bottom: 0,
      flexDirection: 'row',
      backgroundColor: colors.nav,
      borderTopWidth: 1,
      borderTopColor: colors.border,
      paddingTop: 6,
      paddingHorizontal: 8,
    },
    bottomTabButton: { flex: 1, alignItems: 'center', paddingVertical: 7, borderRadius: 8 },
    bottomTabButtonActive: { backgroundColor: colors.cardSoft },
    bottomTabButtonCenter: {},
    bottomTabButtonCenterActive: { backgroundColor: colors.cardSoft },
    bottomTabIconWrap: { minHeight: 20, alignItems: 'center', justifyContent: 'center', marginBottom: 1 },
    bottomTabIcon: { fontSize: 14, fontWeight: '800', color: colors.textMuted, marginBottom: 2 },
    bottomTabIconActive: { color: colors.text },
    bottomTabIconOnPrimary: { color: '#FFFFFF' },
    bottomTabText: { fontSize: 11, fontWeight: '700', color: colors.textMuted, letterSpacing: -0.1 },
    bottomTabTextActive: { color: colors.text },
    bottomTabTextOnPrimary: { color: colors.text },

    row: { flexDirection: 'row', gap: 8, flexWrap: 'wrap' },

    calendarPhoneShell: { paddingTop: 6, paddingBottom: 20, paddingHorizontal: 4 },
    calendarPhoneCard: {
      borderRadius: 30, backgroundColor: colors.cardSoft, paddingHorizontal: 18, paddingTop: 20, paddingBottom: 22,
      shadowColor: '#0F172A', shadowOpacity: 0.12, shadowRadius: 18, shadowOffset: { width: 0, height: 12 }, elevation: 10, gap: 16,
    },
    calendarTopRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
    calendarWeekdayTop: { fontSize: 12, color: colors.textMuted, fontWeight: '600', letterSpacing: 0.4 },
    calendarBigDate: { fontSize: 64, lineHeight: 64, color: colors.text, fontWeight: '800', marginTop: 2 },
    calendarYearText: { fontSize: 13, color: colors.textMuted, fontWeight: '600', marginTop: 2 },
    todayPill: {
      borderRadius: 999, backgroundColor: colors.card, paddingHorizontal: 14, paddingVertical: 8,
      shadowColor: '#111827', shadowOpacity: 0.08, shadowRadius: 8, shadowOffset: { width: 0, height: 4 }, elevation: 3,
    },
    todayPillText: { fontSize: 12, color: colors.primary, fontWeight: '700' },
    weekCapsuleRow: { flexDirection: 'row', gap: 8 },
    weekCapsule: { flex: 1, borderRadius: 16, backgroundColor: colors.card, alignItems: 'center', paddingVertical: 8, gap: 3 },
    weekCapsuleActive: { backgroundColor: colors.text },
    weekCapsuleWeek: { fontSize: 11, color: colors.textMuted, fontWeight: '700' },
    weekCapsuleWeekActive: { color: '#CBD5E1' },
    weekCapsuleDay: { fontSize: 16, color: colors.text, fontWeight: '700' },
    weekCapsuleDayActive: { color: '#FFFFFF' },
    scheduleBoard: { flexDirection: 'row', gap: 12, minHeight: 360 },
    timeColumn: { width: 52, paddingTop: 6, gap: 26 },
    timeLabel: { fontSize: 11, color: colors.textMuted, fontWeight: '600' },
    scheduleColumn: { flex: 1, gap: 10 },
    scheduleCard: {
      borderRadius: 20, paddingHorizontal: 14, paddingVertical: 12,
      shadowColor: '#0F172A', shadowOpacity: 0.1, shadowRadius: 10, shadowOffset: { width: 0, height: 6 }, elevation: 4,
    },
    scheduleCardActive: { transform: [{ translateY: -2 }], shadowOpacity: 0.2, shadowRadius: 14, elevation: 8 },
    scheduleCardTop: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 3 },
    scheduleCardTitle: { color: '#FFFFFF', fontSize: 15, fontWeight: '800', flex: 1, marginRight: 8 },
    scheduleCardMenu: { color: '#E5E7EB', fontSize: 18, fontWeight: '700', lineHeight: 18 },
    scheduleCardSubtitle: { color: '#E5E7EB', fontSize: 12, marginBottom: 6, fontWeight: '600' },
    scheduleCardMeta: { color: '#F3F4F6', fontSize: 11, fontWeight: '600', marginTop: 2 },
    emptyScheduleCard: { borderRadius: 18, backgroundColor: colors.card, padding: 16, borderWidth: 1, borderColor: colors.border },
    emptyScheduleTitle: { fontSize: 14, fontWeight: '700', color: colors.text },
    emptyScheduleText: { marginTop: 4, fontSize: 12, color: colors.textMuted },
  });
}
