source "https://rubygems.org"

gem "fastlane", ">= 2.226.0"
gem "cocoapods", "1.16.2"
# Use latest xcodeproj to support Xcode object version 70.
gem "xcodeproj", git: "https://github.com/CocoaPods/Xcodeproj.git"
