import type { Workspace, Tag, Schedule, Memo, AppFile, AppNotification } from './types';

const today = new Date();
const fmt = (d: Date) => d.toISOString().split('T')[0];
const daysAgo = (n: number) => { const d = new Date(today); d.setDate(d.getDate() - n); return fmt(d); };
const daysAhead = (n: number) => { const d = new Date(today); d.setDate(d.getDate() + n); return fmt(d); };

export const SEED_WORKSPACES: Workspace[] = [
  {
    id: 'ws-personal',
    name: '개인 워크스페이스',
    type: 'personal',
    plan: 'free',
    memberCount: 1,
    createdAt: daysAgo(30),
  },
  {
    id: 'ws-team-1',
    name: '디자인 팀',
    type: 'team',
    plan: 'pro',
    description: 'UI/UX 디자인 팀 워크스페이스',
    memberCount: 5,
    createdAt: daysAgo(20),
  },
];

export const SEED_TAGS: Tag[] = [
  { id: 'tag-1', name: '업무', color: '#3B82F6', workspaceId: 'ws-personal' },
  { id: 'tag-2', name: '개인', color: '#22C55E', workspaceId: 'ws-personal' },
  { id: 'tag-3', name: '중요', color: '#EF4444', workspaceId: 'ws-personal' },
  { id: 'tag-4', name: '회의', color: '#8B5CF6', workspaceId: 'ws-personal' },
  { id: 'tag-5', name: '디자인', color: '#EC4899', workspaceId: 'ws-team-1' },
  { id: 'tag-6', name: '개발', color: '#F97316', workspaceId: 'ws-team-1' },
];

export const SEED_SCHEDULES: Schedule[] = [
  {
    id: 'sch-1',
    title: '팀 주간 회의',
    description: '매주 월요일 정기 회의',
    date: fmt(today),
    startTime: '10:00',
    endTime: '11:00',
    status: 'TODO',
    color: '#5B6CF6',
    tagIds: ['tag-1', 'tag-4'],
    workspaceId: 'ws-personal',
    createdAt: daysAgo(5),
    updatedAt: daysAgo(1),
  },
  {
    id: 'sch-2',
    title: '프로젝트 기획서 작성',
    description: '2분기 신규 프로젝트 기획서 초안 작성',
    date: daysAhead(1),
    startTime: '14:00',
    endTime: '16:00',
    status: 'IN_PROGRESS',
    color: '#F97316',
    tagIds: ['tag-1', 'tag-3'],
    workspaceId: 'ws-personal',
    createdAt: daysAgo(3),
    updatedAt: daysAgo(1),
  },
  {
    id: 'sch-3',
    title: '헬스장 운동',
    date: daysAhead(2),
    startTime: '07:00',
    endTime: '08:30',
    status: 'TODO',
    color: '#22C55E',
    tagIds: ['tag-2'],
    workspaceId: 'ws-personal',
    createdAt: daysAgo(2),
    updatedAt: daysAgo(2),
  },
  {
    id: 'sch-4',
    title: '코드 리뷰',
    date: daysAgo(1),
    startTime: '15:00',
    endTime: '16:00',
    status: 'DONE',
    color: '#8B5CF6',
    tagIds: ['tag-1'],
    workspaceId: 'ws-personal',
    createdAt: daysAgo(7),
    updatedAt: daysAgo(1),
  },
  {
    id: 'sch-5',
    title: '디자인 시스템 리뷰',
    date: daysAhead(3),
    startTime: '13:00',
    endTime: '14:00',
    status: 'TODO',
    color: '#EC4899',
    tagIds: ['tag-5'],
    workspaceId: 'ws-team-1',
    createdAt: daysAgo(1),
    updatedAt: daysAgo(1),
  },
];

export const SEED_MEMOS: Memo[] = [
  {
    id: 'memo-1',
    title: '아이디어 노트',
    content: '새로운 기능 아이디어\n- 다크 모드 지원\n- 위젯 기능\n- 팀 채팅 통합\n\n추후 검토 필요',
    isFavorite: true,
    workspaceId: 'ws-personal',
    createdAt: daysAgo(10),
    updatedAt: daysAgo(2),
  },
  {
    id: 'memo-2',
    title: '회의록 2월 15일',
    content: '참석자: 김철수, 이영희, 박민준\n\n안건:\n1. Q1 목표 검토\n2. 리소스 배분\n3. 다음 스프린트 계획\n\n결정사항: 2월 말까지 MVP 완성',
    isFavorite: false,
    workspaceId: 'ws-personal',
    createdAt: daysAgo(5),
    updatedAt: daysAgo(5),
  },
  {
    id: 'memo-3',
    title: '독서 메모 - 클린 코드',
    content: '핵심 원칙:\n- 의미 있는 이름 사용\n- 함수는 한 가지 일만\n- 주석보다 코드로 설명\n- 오류 처리는 별도로',
    isFavorite: true,
    workspaceId: 'ws-personal',
    createdAt: daysAgo(15),
    updatedAt: daysAgo(10),
  },
  {
    id: 'memo-4',
    title: '장보기 목록',
    content: '- 우유\n- 계란\n- 빵\n- 커피\n- 과일 (사과, 바나나)',
    isFavorite: false,
    workspaceId: 'ws-personal',
    createdAt: daysAgo(1),
    updatedAt: daysAgo(1),
  },
];

export const SEED_FILES: AppFile[] = [
  {
    id: 'file-1',
    name: '프로젝트_기획서_v2.pdf',
    type: 'document',
    size: 2456789,
    uri: 'file://documents/project-plan-v2.pdf',
    mimeType: 'application/pdf',
    workspaceId: 'ws-personal',
    createdAt: daysAgo(3),
  },
  {
    id: 'file-2',
    name: '디자인_시안_최종.png',
    type: 'image',
    size: 1234567,
    uri: 'file://images/design-final.png',
    mimeType: 'image/png',
    workspaceId: 'ws-personal',
    createdAt: daysAgo(5),
  },
  {
    id: 'file-3',
    name: '회의록_2월.docx',
    type: 'document',
    size: 345678,
    uri: 'file://documents/meeting-feb.docx',
    mimeType: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    workspaceId: 'ws-personal',
    createdAt: daysAgo(7),
  },
  {
    id: 'file-4',
    name: '팀_사진.jpg',
    type: 'image',
    size: 3456789,
    uri: 'file://images/team-photo.jpg',
    mimeType: 'image/jpeg',
    workspaceId: 'ws-personal',
    createdAt: daysAgo(10),
  },
  {
    id: 'file-5',
    name: '데이터_분석.xlsx',
    type: 'document',
    size: 567890,
    uri: 'file://documents/data-analysis.xlsx',
    mimeType: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    workspaceId: 'ws-personal',
    createdAt: daysAgo(12),
  },
  {
    id: 'file-6',
    name: '로고_에셋.zip',
    type: 'other',
    size: 8901234,
    uri: 'file://other/logo-assets.zip',
    mimeType: 'application/zip',
    workspaceId: 'ws-personal',
    createdAt: daysAgo(14),
  },
];

export const SEED_NOTIFICATIONS: AppNotification[] = [
  {
    id: 'notif-1',
    type: 'schedule',
    title: '일정 알림',
    body: '오늘 팀 주간 회의가 1시간 후 시작됩니다.',
    isRead: false,
    workspaceId: 'ws-personal',
    createdAt: new Date(today.getTime() - 3600000).toISOString(),
  },
  {
    id: 'notif-2',
    type: 'team',
    title: '팀 초대',
    body: '이영희님이 디자인 팀에 초대했습니다.',
    isRead: false,
    workspaceId: 'ws-team-1',
    createdAt: new Date(today.getTime() - 7200000).toISOString(),
  },
  {
    id: 'notif-3',
    type: 'memo',
    title: '메모 공유',
    body: '박민준님이 회의록을 공유했습니다.',
    isRead: true,
    workspaceId: 'ws-personal',
    createdAt: daysAgo(1),
  },
  {
    id: 'notif-4',
    type: 'file',
    title: '파일 업로드',
    body: '새 파일이 업로드되었습니다: 디자인_시안_최종.png',
    isRead: true,
    workspaceId: 'ws-personal',
    createdAt: daysAgo(2),
  },
];
